AppTurismo/Models/actividadModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AppTurismo.Models
{
    public class actividadModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public actividadModel()
        {
            this.reserva = new HashSet<reservaModel>();
        }

        public int idActividad { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        [DisplayFormat(DataFormatString ="${0:N2}")]
        public decimal costo { get; set; }
        public byte cantidadPersonasDescuento { get; set; }
        [DisplayFormat(DataFormatString ="{0:#}%",ApplyFormatInEditMode =true)]
        public byte porcentajeDescuento { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservaModel> reserva { get; set; }
    }
}

AppTurismo/Models/reservaModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AppTurismo.Models
{
    public class reservaModel
    {
        [DisplayName("N°Reserva")]
        public int idReserva { get; set; }
        [DisplayName("Fecha")]
        [DisplayFormat(DataFormatString ="{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha { get; set; }
        [DisplayName("Actividad")]
        public int idActividad { get; set; }
        [DisplayName("Cliente")]
        public string nombreCliente { get; set; }
        [DisplayName("Teléfono")]
        public string numeroContactoCliente { get; set; }
        [DisplayName("Cantidad de personas")]
        public byte cantidadPersonas { get; set; }
        [DisplayName("Total")]
        public decimal total { get; set; }
        [DisplayName("Nombre de Usuario")]
        public int idUsuario { get; set; }

        public virtual actividadModel actividad { get; set; }
        public virtual usuarioModel usuario { get; set; }
    }
}

AppTurismo/Models/usuarioModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AppTurismo.Models
{
    public class usuarioModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarioModel()
        {
            this.reserva = new HashSet<reservaModel>();
        }

        public int idUsuario { get; set; }
        public string nombreCompleto { get; set; }
        public string email { get; set; }
        public string contrasenna { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservaModel> reserva { get; set; }
    }
}

AppTurismo/Controllers/ActividadController.cs
using AppTurismo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace AppTurismo.Controllers
{
    public class ActividadController : Controller
    {
        // GET: Actividad
        /// <summary>
        /// Este ActionResult me devuelve todas las actividades disponibles por la API
        /// para que el usuario las pueda seleccionar
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //Esta es la lista en la que se van a guardar las Actividades para agregarlas al modelo
            IEnumerable<actividadModel> listaActividades;
            //El response message realiza la comunicación con la API haciendo uso de la clase GlobalVariables
            //GetAsync: Es el metódo que permite obtener(GET) desde la Uri enviada en este caso la Uri en la API es ...api/actividad
            //Result: Es una tarea de HTTP que permite recolectar lo que tenga el cliente de la consulta
            HttpResponseMessage responseMessage = GlobalVariables.WebApiCliente.GetAsync("actividad").Result;
            //Guarda la respuesta que encontró para hacerla visible con el modelo en la vista
            listaActividades = responseMessage.Content.ReadAsAsync<IEnumerable<actividadModel>>().Result;
            //Retornamos la vista con la lista para mostrar los datos desde la API
            return View(listaActividades);
        }
    }
}

AppTurismo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppTurismo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AppTurismo/Controllers/ReservaController.cs
using AppTurismo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace AppTurismo.Controllers
{
    public class ReservaController : Controller
    {
        // GET: Reserva
        /// <summary>
        /// Este ActionResult me devuelve la Lista de todas las reservas en el Inicio
        /// Eso si esta vez consumiendo los datos de la API
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //Declaro un enumerable para almacenar los objetos desde el HTTP
            IEnumerable<reservaModel> listaReservas;
            //El response message realiza la comunicación con la API haciendo uso de la clase GlobalVariables
            //GetAsync: Es el metódo que permite obtener(GET) desde la Uri enviada en este caso la Uri en la API es ...api/reserva
            //Result: Es una tarea de HTTP que permite recolectar lo que tenga el cliente de la consulta
            HttpResponseMessage responseMessage = GlobalVariables.WebApiCliente.GetAsync("reserva").Result;
            //listaReservas: Guarda la respuesta que encontró para hacerla visible con el modelo en la vista
            listaReservas = responseMessage.Content.ReadAsAsync<IEnumerable<reservaModel>>().Result;
            //Retornamos la vista con la lista para mostrar los datos desde la API
            return View(listaReservas);
        }
        /// <summary>
        /// AcitonResult que me envia a registrar una actividad por medio de 
        /// un PUT en la API
        /// </summary>
        /// <returns></returns>
        public ActionResult Reservar()
        {
            return View("Index");
        }
    }
}

AppTurismo/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppTurismo.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }
    }
}

AppTurismo/Views/Actividad/Index.cshtml
@model IEnumerable<AppTurismo.Models.actividadModel>

@{
    ViewBag.Title = "Index";
}

<h2>Actividades</h2><br />
<h3>Seleccione actividades para registrar una reserva</h3>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="row">
    @foreach (var item in Model)
    {

        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card text-center h-100" style="border:medium; border-color:dimgray">
                <div class="card-body">
                    <h4 class="card-title">
                        @Html.DisplayFor(modelItem => item.nombre)
                    </h4>
                    <p class="card-text">
                        @Html.DisplayFor(modelItem => item.costo)
                    </p>
                    <p class="card-text">
                        <b>Descuento:</b> @Html.DisplayFor(modelItem => item.cantidadPersonasDescuento) persona para un @Html.DisplayFor(modelItem => item.porcentajeDescuento)
                    </p>

                </div>
                <div class="card-footer">
                    <a href="@Url.Action("Reservar", "Reserva", new { id = item.idActividad })" class="btn btn-info">Reservar</a>
                </div>
            </div>
        </div> 
}
</div>

AppTurismo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AppTurismo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AppTurismo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AppTurismo/Views/Reserva/Index.cshtml
@model IEnumerable<AppTurismo.Models.reservaModel>

@{
    ViewBag.Title = "Lista de reservas";
}

<h2>Lista de reservas</h2><br />
<h5>Las reservas hasta la fecha registradas</h5>

<p>
    @Html.ActionLink("Registrar una nueva reserva", "Reservar", null, new { @class = "alert-link" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.idReserva)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.idActividad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombreCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.numeroContactoCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cantidadPersonas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.idUsuario)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.idReserva)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.actividad.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nombreCliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.numeroContactoCliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cantidadPersonas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.total)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.usuario.nombreCompleto)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

AppTurismo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - App Turismo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top bg-info">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ejemplo Web API Turismo", "Index", "Actividad", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Reservas", "Index", "Reserva")</li>
                    <li>@Html.ActionLink("Actividades", "Index", "Actividad")</li>
                    <li>@Html.ActionLink("Sobre nosotros", "Contact", "Home")</li>                  
                    <li><a href="@Url.Action("Index", "Usuario", new { @class="align-content-md-end"})"> <i class="fa fa-user"></i>  Usuario</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Web API Exposición APPTurismo ISW-711|2020</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>